version: '2'
services:
  db:
    image: 'bitnami/postgresql:12'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data_12:/bitnami/postgresql12'
    env_file:
      - ./.env.db
volumes:
  postgresql_data_12:
